// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendJobEvent = `-- name: AppendJobEvent :one
INSERT INTO job_events (
  job_id,
  type,
  message,
  progress,
  data
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, job_id, type, message, level, progress, data, created_at
`

type AppendJobEventParams struct {
	JobID    uuid.UUID        `json:"job_id"`
	Type     JobEventTypeEnum `json:"type"`
	Message  string           `json:"message"`
	Progress float64          `json:"progress"`
	Data     []byte           `json:"data"`
}

func (q *Queries) AppendJobEvent(ctx context.Context, arg AppendJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, appendJobEvent,
		arg.JobID,
		arg.Type,
		arg.Message,
		arg.Progress,
		arg.Data,
	)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.Message,
		&i.Level,
		&i.Progress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listJobEventsByJobID = `-- name: ListJobEventsByJobID :many
SELECT id, job_id, type, message, level, progress, data, created_at
FROM job_events
WHERE job_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListJobEventsByJobID(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEventsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Type,
			&i.Message,
			&i.Level,
			&i.Progress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEventsByJobIDFromCursor = `-- name: ListJobEventsByJobIDFromCursor :many
SELECT id, job_id, type, message, level, progress, data, created_at
FROM job_events
WHERE job_id = $1
  AND (created_at, id) > ($2, $3::uuid)
ORDER BY created_at ASC, id ASC
`

type ListJobEventsByJobIDFromCursorParams struct {
	JobID     uuid.UUID        `json:"job_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Column3   uuid.UUID        `json:"column_3"`
}

func (q *Queries) ListJobEventsByJobIDFromCursor(ctx context.Context, arg ListJobEventsByJobIDFromCursorParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEventsByJobIDFromCursor, arg.JobID, arg.CreatedAt, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Type,
			&i.Message,
			&i.Level,
			&i.Progress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
