// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  app_id,
  account_id,
  schema_id,
  schema_version_id,
  toolset_version_id,
  status,
  idempotency_key,
  rerun_of_job_id,
  audio_uri,
  audio_size,
  audio_duration_ms,
  audio_content_type,
  config_snapshot,
  llm_config,
  error_message,
  started_at,
  completed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
`

type CreateJobParams struct {
	AppID            uuid.UUID        `json:"app_id"`
	AccountID        uuid.UUID        `json:"account_id"`
	SchemaID         uuid.UUID        `json:"schema_id"`
	SchemaVersionID  uuid.UUID        `json:"schema_version_id"`
	ToolsetVersionID uuid.UUID        `json:"toolset_version_id"`
	Status           JobStatusEnum    `json:"status"`
	IdempotencyKey   *string          `json:"idempotency_key"`
	RerunOfJobID     pgtype.UUID      `json:"rerun_of_job_id"`
	AudioUri         string           `json:"audio_uri"`
	AudioSize        int64            `json:"audio_size"`
	AudioDurationMs  int64            `json:"audio_duration_ms"`
	AudioContentType string           `json:"audio_content_type"`
	ConfigSnapshot   []byte           `json:"config_snapshot"`
	LlmConfig        []byte           `json:"llm_config"`
	ErrorMessage     *string          `json:"error_message"`
	StartedAt        pgtype.Timestamp `json:"started_at"`
	CompletedAt      pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.AppID,
		arg.AccountID,
		arg.SchemaID,
		arg.SchemaVersionID,
		arg.ToolsetVersionID,
		arg.Status,
		arg.IdempotencyKey,
		arg.RerunOfJobID,
		arg.AudioUri,
		arg.AudioSize,
		arg.AudioDurationMs,
		arg.AudioContentType,
		arg.ConfigSnapshot,
		arg.LlmConfig,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.SchemaVersionID,
		&i.ToolsetVersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.RerunOfJobID,
		&i.AudioUri,
		&i.AudioSize,
		&i.AudioDurationMs,
		&i.AudioContentType,
		&i.ConfigSnapshot,
		&i.LlmConfig,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchemaID,
	)
	return i, err
}

const createRerunJob = `-- name: CreateRerunJob :one
INSERT INTO jobs (
  app_id,
  account_id,
  schema_id,
  schema_version_id,
  toolset_version_id,
  status,
  idempotency_key,
  rerun_of_job_id,
  audio_uri,
  audio_size,
  audio_duration_ms,
  audio_content_type,
  config_snapshot,
  llm_config
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
`

type CreateRerunJobParams struct {
	AppID            uuid.UUID     `json:"app_id"`
	AccountID        uuid.UUID     `json:"account_id"`
	SchemaID         uuid.UUID     `json:"schema_id"`
	SchemaVersionID  uuid.UUID     `json:"schema_version_id"`
	ToolsetVersionID uuid.UUID     `json:"toolset_version_id"`
	Status           JobStatusEnum `json:"status"`
	IdempotencyKey   *string       `json:"idempotency_key"`
	RerunOfJobID     pgtype.UUID   `json:"rerun_of_job_id"`
	AudioUri         string        `json:"audio_uri"`
	AudioSize        int64         `json:"audio_size"`
	AudioDurationMs  int64         `json:"audio_duration_ms"`
	AudioContentType string        `json:"audio_content_type"`
	ConfigSnapshot   []byte        `json:"config_snapshot"`
	LlmConfig        []byte        `json:"llm_config"`
}

func (q *Queries) CreateRerunJob(ctx context.Context, arg CreateRerunJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createRerunJob,
		arg.AppID,
		arg.AccountID,
		arg.SchemaID,
		arg.SchemaVersionID,
		arg.ToolsetVersionID,
		arg.Status,
		arg.IdempotencyKey,
		arg.RerunOfJobID,
		arg.AudioUri,
		arg.AudioSize,
		arg.AudioDurationMs,
		arg.AudioContentType,
		arg.ConfigSnapshot,
		arg.LlmConfig,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.SchemaVersionID,
		&i.ToolsetVersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.RerunOfJobID,
		&i.AudioUri,
		&i.AudioSize,
		&i.AudioDurationMs,
		&i.AudioContentType,
		&i.ConfigSnapshot,
		&i.LlmConfig,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchemaID,
	)
	return i, err
}

const getAppRuntimeBundle = `-- name: GetAppRuntimeBundle :one
SELECT
  a.id,
  a.account_id,
  a.schema_id,
  a.active_schema_version_id,
  a.active_toolset_version_id,
  a.processing_config,
  a.runtime_behavior,
  a.llm_config
FROM apps a
JOIN schema_versions sv
  ON sv.id = a.active_schema_version_id
 AND sv.schema_id = a.schema_id
JOIN toolset_versions tsv
  ON tsv.id = a.active_toolset_version_id
 AND tsv.app_id = a.id
WHERE a.id = $1
  AND a.account_id = $2
`

type GetAppRuntimeBundleParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

type GetAppRuntimeBundleRow struct {
	ID                     uuid.UUID `json:"id"`
	AccountID              uuid.UUID `json:"account_id"`
	SchemaID               uuid.UUID `json:"schema_id"`
	ActiveSchemaVersionID  uuid.UUID `json:"active_schema_version_id"`
	ActiveToolsetVersionID uuid.UUID `json:"active_toolset_version_id"`
	ProcessingConfig       []byte    `json:"processing_config"`
	RuntimeBehavior        []byte    `json:"runtime_behavior"`
	LlmConfig              []byte    `json:"llm_config"`
}

func (q *Queries) GetAppRuntimeBundle(ctx context.Context, arg GetAppRuntimeBundleParams) (GetAppRuntimeBundleRow, error) {
	row := q.db.QueryRow(ctx, getAppRuntimeBundle, arg.ID, arg.AccountID)
	var i GetAppRuntimeBundleRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SchemaID,
		&i.ActiveSchemaVersionID,
		&i.ActiveToolsetVersionID,
		&i.ProcessingConfig,
		&i.RuntimeBehavior,
		&i.LlmConfig,
	)
	return i, err
}

const getJobByIDScoped = `-- name: GetJobByIDScoped :one
SELECT id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
FROM jobs
WHERE id = $1
  AND app_id = $2
  AND account_id = $3
`

type GetJobByIDScopedParams struct {
	ID        uuid.UUID `json:"id"`
	AppID     uuid.UUID `json:"app_id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) GetJobByIDScoped(ctx context.Context, arg GetJobByIDScopedParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIDScoped, arg.ID, arg.AppID, arg.AccountID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.SchemaVersionID,
		&i.ToolsetVersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.RerunOfJobID,
		&i.AudioUri,
		&i.AudioSize,
		&i.AudioDurationMs,
		&i.AudioContentType,
		&i.ConfigSnapshot,
		&i.LlmConfig,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchemaID,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
FROM jobs
WHERE app_id = $1
  AND idempotency_key = $2
`

type GetJobByIdempotencyKeyParams struct {
	AppID          uuid.UUID `json:"app_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.AppID, arg.IdempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.SchemaVersionID,
		&i.ToolsetVersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.RerunOfJobID,
		&i.AudioUri,
		&i.AudioSize,
		&i.AudioDurationMs,
		&i.AudioContentType,
		&i.ConfigSnapshot,
		&i.LlmConfig,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchemaID,
	)
	return i, err
}

const listJobsBeforeCursor = `-- name: ListJobsBeforeCursor :many
SELECT id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
FROM jobs
WHERE app_id = $1
  AND account_id = $2
  AND (created_at, id) < ($3, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListJobsBeforeCursorParams struct {
	AppID     uuid.UUID        `json:"app_id"`
	AccountID uuid.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Column4   uuid.UUID        `json:"column_4"`
	Limit     int32            `json:"limit"`
}

func (q *Queries) ListJobsBeforeCursor(ctx context.Context, arg ListJobsBeforeCursorParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsBeforeCursor,
		arg.AppID,
		arg.AccountID,
		arg.CreatedAt,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.SchemaVersionID,
			&i.ToolsetVersionID,
			&i.Status,
			&i.IdempotencyKey,
			&i.RerunOfJobID,
			&i.AudioUri,
			&i.AudioSize,
			&i.AudioDurationMs,
			&i.AudioContentType,
			&i.ConfigSnapshot,
			&i.LlmConfig,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchemaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByAppAccount = `-- name: ListJobsByAppAccount :many
SELECT id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
FROM jobs
WHERE app_id = $1
  AND account_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListJobsByAppAccountParams struct {
	AppID     uuid.UUID `json:"app_id"`
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListJobsByAppAccount(ctx context.Context, arg ListJobsByAppAccountParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByAppAccount, arg.AppID, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.SchemaVersionID,
			&i.ToolsetVersionID,
			&i.Status,
			&i.IdempotencyKey,
			&i.RerunOfJobID,
			&i.AudioUri,
			&i.AudioSize,
			&i.AudioDurationMs,
			&i.AudioContentType,
			&i.ConfigSnapshot,
			&i.LlmConfig,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchemaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2,
    error_message = $3,
    started_at = COALESCE($4, started_at),
    completed_at = COALESCE($5, completed_at),
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, account_id, schema_version_id, toolset_version_id, status, idempotency_key, rerun_of_job_id, audio_uri, audio_size, audio_duration_ms, audio_content_type, config_snapshot, llm_config, error_message, started_at, completed_at, created_at, updated_at, schema_id
`

type UpdateJobStatusParams struct {
	ID           uuid.UUID        `json:"id"`
	Status       JobStatusEnum    `json:"status"`
	ErrorMessage *string          `json:"error_message"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.SchemaVersionID,
		&i.ToolsetVersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.RerunOfJobID,
		&i.AudioUri,
		&i.AudioSize,
		&i.AudioDurationMs,
		&i.AudioContentType,
		&i.ConfigSnapshot,
		&i.LlmConfig,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchemaID,
	)
	return i, err
}
