// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CitationTargetTypeEnum string

const (
	CitationTargetTypeEnumExtractedItem  CitationTargetTypeEnum = "extracted_item"
	CitationTargetTypeEnumToolSuggestion CitationTargetTypeEnum = "tool_suggestion"
)

func (e *CitationTargetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CitationTargetTypeEnum(s)
	case string:
		*e = CitationTargetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CitationTargetTypeEnum: %T", src)
	}
	return nil
}

type NullCitationTargetTypeEnum struct {
	CitationTargetTypeEnum CitationTargetTypeEnum `json:"citation_target_type_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if CitationTargetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCitationTargetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CitationTargetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CitationTargetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCitationTargetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CitationTargetTypeEnum), nil
}

type ExtractionRunStatusEnum string

const (
	ExtractionRunStatusEnumQueued    ExtractionRunStatusEnum = "queued"
	ExtractionRunStatusEnumRunning   ExtractionRunStatusEnum = "running"
	ExtractionRunStatusEnumSucceeded ExtractionRunStatusEnum = "succeeded"
	ExtractionRunStatusEnumFailed    ExtractionRunStatusEnum = "failed"
)

func (e *ExtractionRunStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExtractionRunStatusEnum(s)
	case string:
		*e = ExtractionRunStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ExtractionRunStatusEnum: %T", src)
	}
	return nil
}

type NullExtractionRunStatusEnum struct {
	ExtractionRunStatusEnum ExtractionRunStatusEnum `json:"extraction_run_status_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if ExtractionRunStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExtractionRunStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ExtractionRunStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExtractionRunStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExtractionRunStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExtractionRunStatusEnum), nil
}

type JobEventLevelEnum string

const (
	JobEventLevelEnumDebug JobEventLevelEnum = "debug"
	JobEventLevelEnumInfo  JobEventLevelEnum = "info"
	JobEventLevelEnumWarn  JobEventLevelEnum = "warn"
	JobEventLevelEnumError JobEventLevelEnum = "error"
)

func (e *JobEventLevelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobEventLevelEnum(s)
	case string:
		*e = JobEventLevelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobEventLevelEnum: %T", src)
	}
	return nil
}

type NullJobEventLevelEnum struct {
	JobEventLevelEnum JobEventLevelEnum `json:"job_event_level_enum"`
	Valid             bool              `json:"valid"` // Valid is true if JobEventLevelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobEventLevelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobEventLevelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobEventLevelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobEventLevelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobEventLevelEnum), nil
}

type JobEventTypeEnum string

const (
	JobEventTypeEnumAccepted                JobEventTypeEnum = "accepted"
	JobEventTypeEnumIngestStarted           JobEventTypeEnum = "ingest_started"
	JobEventTypeEnumIngestCompleted         JobEventTypeEnum = "ingest_completed"
	JobEventTypeEnumTranscriptionStarted    JobEventTypeEnum = "transcription_started"
	JobEventTypeEnumTranscriptionCompleted  JobEventTypeEnum = "transcription_completed"
	JobEventTypeEnumExtractionStarted       JobEventTypeEnum = "extraction_started"
	JobEventTypeEnumExtractionCompleted     JobEventTypeEnum = "extraction_completed"
	JobEventTypeEnumToolSuggestionStarted   JobEventTypeEnum = "tool_suggestion_started"
	JobEventTypeEnumToolSuggestionCompleted JobEventTypeEnum = "tool_suggestion_completed"
	JobEventTypeEnumCompleted               JobEventTypeEnum = "completed"
	JobEventTypeEnumFailed                  JobEventTypeEnum = "failed"
	JobEventTypeEnumCancelled               JobEventTypeEnum = "cancelled"
	JobEventTypeEnumProgress                JobEventTypeEnum = "progress"
	JobEventTypeEnumSttStarted              JobEventTypeEnum = "stt_started"
)

func (e *JobEventTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobEventTypeEnum(s)
	case string:
		*e = JobEventTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobEventTypeEnum: %T", src)
	}
	return nil
}

type NullJobEventTypeEnum struct {
	JobEventTypeEnum JobEventTypeEnum `json:"job_event_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if JobEventTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobEventTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobEventTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobEventTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobEventTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobEventTypeEnum), nil
}

type JobStatusEnum string

const (
	JobStatusEnumQueued    JobStatusEnum = "queued"
	JobStatusEnumRunning   JobStatusEnum = "running"
	JobStatusEnumSucceeded JobStatusEnum = "succeeded"
	JobStatusEnumFailed    JobStatusEnum = "failed"
	JobStatusEnumCancelled JobStatusEnum = "cancelled"
)

func (e *JobStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusEnum(s)
	case string:
		*e = JobStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusEnum: %T", src)
	}
	return nil
}

type NullJobStatusEnum struct {
	JobStatusEnum JobStatusEnum `json:"job_status_enum"`
	Valid         bool          `json:"valid"` // Valid is true if JobStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatusEnum), nil
}

type JobStepStatusEnum string

const (
	JobStepStatusEnumQueued    JobStepStatusEnum = "queued"
	JobStepStatusEnumRunning   JobStepStatusEnum = "running"
	JobStepStatusEnumSucceeded JobStepStatusEnum = "succeeded"
	JobStepStatusEnumFailed    JobStepStatusEnum = "failed"
	JobStepStatusEnumCancelled JobStepStatusEnum = "cancelled"
	JobStepStatusEnumSkipped   JobStepStatusEnum = "skipped"
)

func (e *JobStepStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStepStatusEnum(s)
	case string:
		*e = JobStepStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStepStatusEnum: %T", src)
	}
	return nil
}

type NullJobStepStatusEnum struct {
	JobStepStatusEnum JobStepStatusEnum `json:"job_step_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if JobStepStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStepStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobStepStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStepStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStepStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStepStatusEnum), nil
}

type MediaAssetKindEnum string

const (
	MediaAssetKindEnumSourceAudio     MediaAssetKindEnum = "source_audio"
	MediaAssetKindEnumNormalizedAudio MediaAssetKindEnum = "normalized_audio"
	MediaAssetKindEnumPreview         MediaAssetKindEnum = "preview"
	MediaAssetKindEnumThumbnail       MediaAssetKindEnum = "thumbnail"
	MediaAssetKindEnumWaveform        MediaAssetKindEnum = "waveform"
)

func (e *MediaAssetKindEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaAssetKindEnum(s)
	case string:
		*e = MediaAssetKindEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaAssetKindEnum: %T", src)
	}
	return nil
}

type NullMediaAssetKindEnum struct {
	MediaAssetKindEnum MediaAssetKindEnum `json:"media_asset_kind_enum"`
	Valid              bool               `json:"valid"` // Valid is true if MediaAssetKindEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaAssetKindEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MediaAssetKindEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaAssetKindEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaAssetKindEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaAssetKindEnum), nil
}

type SchemaVersionStatusEnum string

const (
	SchemaVersionStatusEnumDraft      SchemaVersionStatusEnum = "draft"
	SchemaVersionStatusEnumActive     SchemaVersionStatusEnum = "active"
	SchemaVersionStatusEnumDeprecated SchemaVersionStatusEnum = "deprecated"
)

func (e *SchemaVersionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchemaVersionStatusEnum(s)
	case string:
		*e = SchemaVersionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SchemaVersionStatusEnum: %T", src)
	}
	return nil
}

type NullSchemaVersionStatusEnum struct {
	SchemaVersionStatusEnum SchemaVersionStatusEnum `json:"schema_version_status_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if SchemaVersionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchemaVersionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SchemaVersionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchemaVersionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchemaVersionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchemaVersionStatusEnum), nil
}

type ToolSuggestionRunStatusEnum string

const (
	ToolSuggestionRunStatusEnumQueued    ToolSuggestionRunStatusEnum = "queued"
	ToolSuggestionRunStatusEnumRunning   ToolSuggestionRunStatusEnum = "running"
	ToolSuggestionRunStatusEnumSucceeded ToolSuggestionRunStatusEnum = "succeeded"
	ToolSuggestionRunStatusEnumFailed    ToolSuggestionRunStatusEnum = "failed"
)

func (e *ToolSuggestionRunStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolSuggestionRunStatusEnum(s)
	case string:
		*e = ToolSuggestionRunStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolSuggestionRunStatusEnum: %T", src)
	}
	return nil
}

type NullToolSuggestionRunStatusEnum struct {
	ToolSuggestionRunStatusEnum ToolSuggestionRunStatusEnum `json:"tool_suggestion_run_status_enum"`
	Valid                       bool                        `json:"valid"` // Valid is true if ToolSuggestionRunStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolSuggestionRunStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ToolSuggestionRunStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolSuggestionRunStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolSuggestionRunStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolSuggestionRunStatusEnum), nil
}

type ToolSuggestionStatusEnum string

const (
	ToolSuggestionStatusEnumPending   ToolSuggestionStatusEnum = "pending"
	ToolSuggestionStatusEnumSuggested ToolSuggestionStatusEnum = "suggested"
	ToolSuggestionStatusEnumAccepted  ToolSuggestionStatusEnum = "accepted"
	ToolSuggestionStatusEnumRejected  ToolSuggestionStatusEnum = "rejected"
	ToolSuggestionStatusEnumExecuted  ToolSuggestionStatusEnum = "executed"
	ToolSuggestionStatusEnumFailed    ToolSuggestionStatusEnum = "failed"
)

func (e *ToolSuggestionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolSuggestionStatusEnum(s)
	case string:
		*e = ToolSuggestionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolSuggestionStatusEnum: %T", src)
	}
	return nil
}

type NullToolSuggestionStatusEnum struct {
	ToolSuggestionStatusEnum ToolSuggestionStatusEnum `json:"tool_suggestion_status_enum"`
	Valid                    bool                     `json:"valid"` // Valid is true if ToolSuggestionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolSuggestionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ToolSuggestionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolSuggestionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolSuggestionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolSuggestionStatusEnum), nil
}

type ToolVersionStatusEnum string

const (
	ToolVersionStatusEnumDraft      ToolVersionStatusEnum = "draft"
	ToolVersionStatusEnumActive     ToolVersionStatusEnum = "active"
	ToolVersionStatusEnumDeprecated ToolVersionStatusEnum = "deprecated"
)

func (e *ToolVersionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolVersionStatusEnum(s)
	case string:
		*e = ToolVersionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolVersionStatusEnum: %T", src)
	}
	return nil
}

type NullToolVersionStatusEnum struct {
	ToolVersionStatusEnum ToolVersionStatusEnum `json:"tool_version_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if ToolVersionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolVersionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ToolVersionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolVersionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolVersionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolVersionStatusEnum), nil
}

type ToolsetVersionStatusEnum string

const (
	ToolsetVersionStatusEnumDraft      ToolsetVersionStatusEnum = "draft"
	ToolsetVersionStatusEnumActive     ToolsetVersionStatusEnum = "active"
	ToolsetVersionStatusEnumDeprecated ToolsetVersionStatusEnum = "deprecated"
)

func (e *ToolsetVersionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolsetVersionStatusEnum(s)
	case string:
		*e = ToolsetVersionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolsetVersionStatusEnum: %T", src)
	}
	return nil
}

type NullToolsetVersionStatusEnum struct {
	ToolsetVersionStatusEnum ToolsetVersionStatusEnum `json:"toolset_version_status_enum"`
	Valid                    bool                     `json:"valid"` // Valid is true if ToolsetVersionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolsetVersionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ToolsetVersionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolsetVersionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolsetVersionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolsetVersionStatusEnum), nil
}

type TranscriptProviderEnum string

const (
	TranscriptProviderEnumDeepgram     TranscriptProviderEnum = "deepgram"
	TranscriptProviderEnumSpeechmatics TranscriptProviderEnum = "speechmatics"
	TranscriptProviderEnumManual       TranscriptProviderEnum = "manual"
)

func (e *TranscriptProviderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptProviderEnum(s)
	case string:
		*e = TranscriptProviderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptProviderEnum: %T", src)
	}
	return nil
}

type NullTranscriptProviderEnum struct {
	TranscriptProviderEnum TranscriptProviderEnum `json:"transcript_provider_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if TranscriptProviderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptProviderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptProviderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptProviderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptProviderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptProviderEnum), nil
}

type TranscriptStatusEnum string

const (
	TranscriptStatusEnumQueued    TranscriptStatusEnum = "queued"
	TranscriptStatusEnumRunning   TranscriptStatusEnum = "running"
	TranscriptStatusEnumSucceeded TranscriptStatusEnum = "succeeded"
	TranscriptStatusEnumFailed    TranscriptStatusEnum = "failed"
)

func (e *TranscriptStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptStatusEnum(s)
	case string:
		*e = TranscriptStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptStatusEnum: %T", src)
	}
	return nil
}

type NullTranscriptStatusEnum struct {
	TranscriptStatusEnum TranscriptStatusEnum `json:"transcript_status_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if TranscriptStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptStatusEnum), nil
}

type UsageEventTypeEnum string

const (
	UsageEventTypeEnumSttAudioMs     UsageEventTypeEnum = "stt_audio_ms"
	UsageEventTypeEnumLlmTokens      UsageEventTypeEnum = "llm_tokens"
	UsageEventTypeEnumJobProcessed   UsageEventTypeEnum = "job_processed"
	UsageEventTypeEnumWebhookAttempt UsageEventTypeEnum = "webhook_attempt"
)

func (e *UsageEventTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsageEventTypeEnum(s)
	case string:
		*e = UsageEventTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UsageEventTypeEnum: %T", src)
	}
	return nil
}

type NullUsageEventTypeEnum struct {
	UsageEventTypeEnum UsageEventTypeEnum `json:"usage_event_type_enum"`
	Valid              bool               `json:"valid"` // Valid is true if UsageEventTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsageEventTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UsageEventTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsageEventTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsageEventTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsageEventTypeEnum), nil
}

type WebhookDeliveryStatusEnum string

const (
	WebhookDeliveryStatusEnumPending   WebhookDeliveryStatusEnum = "pending"
	WebhookDeliveryStatusEnumRetrying  WebhookDeliveryStatusEnum = "retrying"
	WebhookDeliveryStatusEnumSucceeded WebhookDeliveryStatusEnum = "succeeded"
	WebhookDeliveryStatusEnumFailed    WebhookDeliveryStatusEnum = "failed"
)

func (e *WebhookDeliveryStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveryStatusEnum(s)
	case string:
		*e = WebhookDeliveryStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveryStatusEnum: %T", src)
	}
	return nil
}

type NullWebhookDeliveryStatusEnum struct {
	WebhookDeliveryStatusEnum WebhookDeliveryStatusEnum `json:"webhook_delivery_status_enum"`
	Valid                     bool                      `json:"valid"` // Valid is true if WebhookDeliveryStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveryStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveryStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveryStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveryStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveryStatusEnum), nil
}

type WebhookEventTypeEnum string

const (
	WebhookEventTypeEnumJobProgress  WebhookEventTypeEnum = "job_progress"
	WebhookEventTypeEnumJobCompleted WebhookEventTypeEnum = "job_completed"
	WebhookEventTypeEnumJobFailed    WebhookEventTypeEnum = "job_failed"
)

func (e *WebhookEventTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookEventTypeEnum(s)
	case string:
		*e = WebhookEventTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookEventTypeEnum: %T", src)
	}
	return nil
}

type NullWebhookEventTypeEnum struct {
	WebhookEventTypeEnum WebhookEventTypeEnum `json:"webhook_event_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if WebhookEventTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookEventTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookEventTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookEventTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookEventTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookEventTypeEnum), nil
}

type Account struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ApiKey struct {
	ID         uuid.UUID        `json:"id"`
	AppID      uuid.UUID        `json:"app_id"`
	AccountID  uuid.UUID        `json:"account_id"`
	Name       string           `json:"name"`
	KeyHash    string           `json:"key_hash"`
	KeyPrefix  string           `json:"key_prefix"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	RevokedAt  pgtype.Timestamp `json:"revoked_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type App struct {
	ID                     uuid.UUID        `json:"id"`
	AccountID              uuid.UUID        `json:"account_id"`
	Name                   string           `json:"name"`
	SchemaID               uuid.UUID        `json:"schema_id"`
	ActiveSchemaVersionID  uuid.UUID        `json:"active_schema_version_id"`
	ActiveToolsetVersionID uuid.UUID        `json:"active_toolset_version_id"`
	ProcessingConfig       []byte           `json:"processing_config"`
	RuntimeBehavior        []byte           `json:"runtime_behavior"`
	LlmConfig              []byte           `json:"llm_config"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}

type Citation struct {
	ID                  uuid.UUID              `json:"id"`
	TranscriptSegmentID uuid.UUID              `json:"transcript_segment_id"`
	TargetType          CitationTargetTypeEnum `json:"target_type"`
	TargetID            uuid.UUID              `json:"target_id"`
	StartMs             *int64                 `json:"start_ms"`
	EndMs               *int64                 `json:"end_ms"`
	CreatedAt           pgtype.Timestamp       `json:"created_at"`
}

type ExtractedItem struct {
	ID              uuid.UUID        `json:"id"`
	ExtractionRunID uuid.UUID        `json:"extraction_run_id"`
	ItemKey         string           `json:"item_key"`
	ItemType        string           `json:"item_type"`
	Payload         []byte           `json:"payload"`
	Confidence      *float64         `json:"confidence"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type ExtractionRun struct {
	ID              uuid.UUID               `json:"id"`
	JobID           uuid.UUID               `json:"job_id"`
	SchemaVersionID uuid.UUID               `json:"schema_version_id"`
	Status          ExtractionRunStatusEnum `json:"status"`
	ErrorMessage    *string                 `json:"error_message"`
	StartedAt       pgtype.Timestamp        `json:"started_at"`
	CompletedAt     pgtype.Timestamp        `json:"completed_at"`
	CreatedAt       pgtype.Timestamp        `json:"created_at"`
	UpdatedAt       pgtype.Timestamp        `json:"updated_at"`
}

type Job struct {
	ID               uuid.UUID        `json:"id"`
	AppID            uuid.UUID        `json:"app_id"`
	AccountID        uuid.UUID        `json:"account_id"`
	SchemaVersionID  uuid.UUID        `json:"schema_version_id"`
	ToolsetVersionID uuid.UUID        `json:"toolset_version_id"`
	Status           JobStatusEnum    `json:"status"`
	IdempotencyKey   *string          `json:"idempotency_key"`
	RerunOfJobID     pgtype.UUID      `json:"rerun_of_job_id"`
	AudioUri         string           `json:"audio_uri"`
	AudioSize        int64            `json:"audio_size"`
	AudioDurationMs  int64            `json:"audio_duration_ms"`
	AudioContentType string           `json:"audio_content_type"`
	ConfigSnapshot   []byte           `json:"config_snapshot"`
	LlmConfig        []byte           `json:"llm_config"`
	ErrorMessage     *string          `json:"error_message"`
	StartedAt        pgtype.Timestamp `json:"started_at"`
	CompletedAt      pgtype.Timestamp `json:"completed_at"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	SchemaID         uuid.UUID        `json:"schema_id"`
}

type JobEvent struct {
	ID        uuid.UUID         `json:"id"`
	JobID     uuid.UUID         `json:"job_id"`
	Type      JobEventTypeEnum  `json:"type"`
	Message   string            `json:"message"`
	Level     JobEventLevelEnum `json:"level"`
	Progress  float64           `json:"progress"`
	Data      []byte            `json:"data"`
	CreatedAt pgtype.Timestamp  `json:"created_at"`
}

type JobStep struct {
	ID           uuid.UUID         `json:"id"`
	JobID        uuid.UUID         `json:"job_id"`
	Step         string            `json:"step"`
	Status       JobStepStatusEnum `json:"status"`
	Message      *string           `json:"message"`
	ErrorMessage *string           `json:"error_message"`
	StartedAt    pgtype.Timestamp  `json:"started_at"`
	CompletedAt  pgtype.Timestamp  `json:"completed_at"`
	CreatedAt    pgtype.Timestamp  `json:"created_at"`
	UpdatedAt    pgtype.Timestamp  `json:"updated_at"`
}

type MediaAsset struct {
	ID          uuid.UUID          `json:"id"`
	JobID       uuid.UUID          `json:"job_id"`
	Kind        MediaAssetKindEnum `json:"kind"`
	Uri         string             `json:"uri"`
	ContentType string             `json:"content_type"`
	SizeBytes   *int64             `json:"size_bytes"`
	DurationMs  *int64             `json:"duration_ms"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamp   `json:"created_at"`
}

type Schema struct {
	ID          uuid.UUID        `json:"id"`
	AccountID   uuid.UUID        `json:"account_id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type SchemaVersion struct {
	ID         uuid.UUID               `json:"id"`
	SchemaID   uuid.UUID               `json:"schema_id"`
	Version    int32                   `json:"version"`
	Status     SchemaVersionStatusEnum `json:"status"`
	Definition []byte                  `json:"definition"`
	CreatedAt  pgtype.Timestamp        `json:"created_at"`
}

type Tool struct {
	ID          uuid.UUID        `json:"id"`
	AppID       uuid.UUID        `json:"app_id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ToolSuggestion struct {
	ID                  uuid.UUID                `json:"id"`
	ToolSuggestionRunID uuid.UUID                `json:"tool_suggestion_run_id"`
	ToolVersionID       pgtype.UUID              `json:"tool_version_id"`
	Status              ToolSuggestionStatusEnum `json:"status"`
	Title               *string                  `json:"title"`
	Payload             []byte                   `json:"payload"`
	Confidence          *float64                 `json:"confidence"`
	CreatedAt           pgtype.Timestamp         `json:"created_at"`
}

type ToolSuggestionRun struct {
	ID           uuid.UUID                   `json:"id"`
	JobID        uuid.UUID                   `json:"job_id"`
	Status       ToolSuggestionRunStatusEnum `json:"status"`
	ErrorMessage *string                     `json:"error_message"`
	StartedAt    pgtype.Timestamp            `json:"started_at"`
	CompletedAt  pgtype.Timestamp            `json:"completed_at"`
	CreatedAt    pgtype.Timestamp            `json:"created_at"`
	UpdatedAt    pgtype.Timestamp            `json:"updated_at"`
}

type ToolVersion struct {
	ID         uuid.UUID             `json:"id"`
	ToolID     uuid.UUID             `json:"tool_id"`
	Version    int32                 `json:"version"`
	Status     ToolVersionStatusEnum `json:"status"`
	Definition []byte                `json:"definition"`
	CreatedAt  pgtype.Timestamp      `json:"created_at"`
}

type Toolset struct {
	ID        uuid.UUID        `json:"id"`
	AppID     uuid.UUID        `json:"app_id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ToolsetVersion struct {
	ID         uuid.UUID                `json:"id"`
	ToolsetID  uuid.UUID                `json:"toolset_id"`
	AppID      uuid.UUID                `json:"app_id"`
	Version    int32                    `json:"version"`
	Status     ToolsetVersionStatusEnum `json:"status"`
	Definition []byte                   `json:"definition"`
	CreatedAt  pgtype.Timestamp         `json:"created_at"`
}

type Transcript struct {
	ID           uuid.UUID              `json:"id"`
	JobID        uuid.UUID              `json:"job_id"`
	Provider     TranscriptProviderEnum `json:"provider"`
	Status       TranscriptStatusEnum   `json:"status"`
	LanguageCode *string                `json:"language_code"`
	FullText     *string                `json:"full_text"`
	Metadata     []byte                 `json:"metadata"`
	CreatedAt    pgtype.Timestamp       `json:"created_at"`
	UpdatedAt    pgtype.Timestamp       `json:"updated_at"`
}

type TranscriptSegment struct {
	ID           uuid.UUID        `json:"id"`
	TranscriptID uuid.UUID        `json:"transcript_id"`
	SegmentIndex int64            `json:"segment_index"`
	SpeakerLabel *string          `json:"speaker_label"`
	StartMs      int64            `json:"start_ms"`
	EndMs        int64            `json:"end_ms"`
	Text         string           `json:"text"`
	Confidence   *float64         `json:"confidence"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type UsageEvent struct {
	ID        uuid.UUID          `json:"id"`
	AppID     uuid.UUID          `json:"app_id"`
	AccountID uuid.UUID          `json:"account_id"`
	JobID     pgtype.UUID        `json:"job_id"`
	Type      UsageEventTypeEnum `json:"type"`
	Metric    []byte             `json:"metric"`
	LoggedAt  pgtype.Timestamp   `json:"logged_at"`
}

type User struct {
	ID          uuid.UUID        `json:"id"`
	AccountID   uuid.UUID        `json:"account_id"`
	Email       string           `json:"email"`
	DisplayName *string          `json:"display_name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Webhook struct {
	ID         uuid.UUID        `json:"id"`
	AppID      uuid.UUID        `json:"app_id"`
	Url        string           `json:"url"`
	SecretHash string           `json:"secret_hash"`
	Enabled    bool             `json:"enabled"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID                 `json:"id"`
	WebhookID    uuid.UUID                 `json:"webhook_id"`
	JobID        pgtype.UUID               `json:"job_id"`
	EventType    WebhookEventTypeEnum      `json:"event_type"`
	Status       WebhookDeliveryStatusEnum `json:"status"`
	ResponseCode *int32                    `json:"response_code"`
	ErrorMessage *string                   `json:"error_message"`
	AttemptedAt  pgtype.Timestamp          `json:"attempted_at"`
	DeliveredAt  pgtype.Timestamp          `json:"delivered_at"`
	CreatedAt    pgtype.Timestamp          `json:"created_at"`
}
