// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AppendJobEvent(ctx context.Context, arg AppendJobEventParams) (JobEvent, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateRerunJob(ctx context.Context, arg CreateRerunJobParams) (Job, error)
	GetAppRuntimeBundle(ctx context.Context, arg GetAppRuntimeBundleParams) (GetAppRuntimeBundleRow, error)
	GetJobByIDScoped(ctx context.Context, arg GetJobByIDScopedParams) (Job, error)
	GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error)
	ListJobEventsByJobID(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error)
	ListJobEventsByJobIDFromCursor(ctx context.Context, arg ListJobEventsByJobIDFromCursorParams) ([]JobEvent, error)
	ListJobsBeforeCursor(ctx context.Context, arg ListJobsBeforeCursorParams) ([]Job, error)
	ListJobsByAppAccount(ctx context.Context, arg ListJobsByAppAccountParams) ([]Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
